### ISSUE TITLE
Git branching model

### ISSUE THREAD

**Issue by Gazentia** [apdraganis/MERN-Ecommerce-App#30]
Hello, I have some idea for git branching model like this photo.
![image](https://user-images.githubusercontent.com/63592674/168552648-a8537caf-6c9e-4cfa-b332-7753fcc9f6d1.png)

For applying in our project. I thought that
1. we should have `develop` branch and let `master or main`  be production branch
2. when we like  to develop new feature we should create new feature branch for it such as `feature/backend-api` , `fix/header-bug`
3. every feature branch that get approve from other we will merge to `develop` branch

**What do you think about this idea?**

**Comment by alexisredd** [comment]
This is one of a good idea for working with Git.

Anyway, we currently use a different approach, we utilize issues for both feature and bug (might using tag to separate it but never discuss yet) 

and we assign a single person/member to take owner of that issue to solve by creating branch on their downstream repo and make a PR based on that branch to main by ref #num of issue on git commit message (this way when PR is merged the issue will be closed automatically) 

so we don't have a develop branch on upstream repo but we have waiting to merge branch for specific feature/bug. Anyway we might change, let's discuss further in discord server

**Comment by apdraganis** [comment]
I'm also ok with this plan guys. I'm closing the issue and we can start implementing it from now on.
