### ISSUE TITLE
Change carousel library

### ISSUE THREAD

**Issue by alexiszuck** [apdraganis/MERN-Ecommerce-App#35]
Currently, we are using (actually, I am the one who pick it) daisyUI's carousel which after merging to the main branch, I was starting to see a bug from clicking the side arrow or clicking the dot nav under the picture, the whole page will scroll up to the position that carousel is on top of the browser frame.

from my understanding, it is because they use <a> with href='#' to slide the carousel image and that comes with the normal behavior of browser scrolling.

This can be annoying and I'd like to find a new library or even code it myself

**Comment by Gazentia** [comment]
let's try check [react-daisyui](https://github.com/daisyui/react-daisyui). Maybe it can help you.

**Comment by alexisredd** [comment]
I finished a custom carousel that looks like the same as daisyUI. going to make PR on this after PR #37 is merged

**Comment by apdraganis** [comment]
I noticed that too alexis. Just merged pr#37, waiting for your pr on this issue
